const admin = require('firebase-admin');
const db = admin.firestore();

// Helper to sync chapter assessments to Gradebook assignments
const syncAssignments = async (courseId, modules) => {
    if (!modules) return;
    for (const module of modules) {
        if (!module.chapters) continue;
        for (const chapter of module.chapters) {
            if (chapter.content && chapter.content.assessmentSection) {
                const assessment = chapter.content.assessmentSection;
                const assignmentId = `assessment_${courseId}_${chapter.id}`;
                await db.collection('assignments').doc(assignmentId).set({
                    courseId,
                    chapterId: chapter.id,
                    title: `${chapter.title} - Assessment`,
                    pointsPossible: assessment.totalScore || 100,
                    passingScore: assessment.passingScore || 70,
                    isAutoGenerated: true,
                    updatedAt: admin.firestore.FieldValue.serverTimestamp()
                }, { merge: true });
            }
        }
    }
};

// Get all courses
exports.getAllCourses = async (req, res) => {
    try {
        let query = db.collection('courses');
        
        if (req.query.instructorId) {
            query = query.where('instructorId', '==', req.query.instructorId);
        }

        const snapshot = await query.get();
        const courses = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
        res.status(200).json(courses);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

// Get a single course
exports.getCourseById = async (req, res) => {
    try {
        const doc = await db.collection('courses').doc(req.params.id).get();
        if (!doc.exists) {
            return res.status(404).json({ message: 'Course not found' });
        }
        const courseData = doc.data();
        let instructorName = "Unknown Instructor";
        if (courseData.instructorId) {
            const instructorDoc = await db.collection('users').doc(courseData.instructorId).get();
            if (instructorDoc.exists) {
                const iData = instructorDoc.data();
                instructorName = iData.displayName || iData.full_name || `${iData.firstName || ''} ${iData.lastName || ''}`.trim() || iData.email || "Instructor";
            }
        }
        res.status(200).json({ id: doc.id, ...courseData, instructorName });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

// Create a new course
exports.createCourse = async (req, res) => {
    try {
        const { title, description, duration, seats, attachments, tags, domain, startDate, level } = req.body;
        const instructorId = req.user.uid; // Get ID from authenticated user

        const newCourse = {
            title,
            description,
            instructorId,
            duration: duration || { value: 0, unit: 'weeks' },
            seats: seats ? parseInt(seats) : 0,
            startDate: startDate || null,
            attachments: attachments || [],
            tags: tags || [],
            domain: domain || 'General',
            level: level || 'Beginner',
            status: req.body.status || 'published',
            modules: req.body.modules || [], // Include modules
            certificate: req.body.certificate || null, // Include certificate config
            createdAt: admin.firestore.FieldValue.serverTimestamp()
        };
        const docRef = await db.collection('courses').add(newCourse);
        
        // Sync assessments to Gradebook
        await syncAssignments(docRef.id, req.body.modules);
        
        res.status(201).json({ id: docRef.id, ...newCourse });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

// Update a course
exports.updateCourse = async (req, res) => {
    try {
        await db.collection('courses').doc(req.params.id).update(req.body);
        
        // Sync assessments to Gradebook
        if (req.body.modules) {
            await syncAssignments(req.params.id, req.body.modules);
        }
        
        res.status(200).json({ message: 'Course updated successfully' });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

// Delete a course
exports.deleteCourse = async (req, res) => {
    try {
        await db.collection('courses').doc(req.params.id).delete();
        res.status(200).json({ message: 'Course deleted successfully' });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};
